include: package:lints/recommended.yaml

linter:
  rules:
    - omit_local_variable_types
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_in_for_each
    - prefer_final_locals
    - sort_pub_dependencies
