name: music_notes
description: Music notes library
version: 0.1.0

author: albertms10
repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  quiver: ^3.0.0-nullsafety.3
  test: ^1.16.0-nullsafety.16
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
