name: music_notes
description: Music notes library
version: 0.1.0

author: albertms10
repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  quiver: ^2.1.5
  test: ^1.14.6

dev_dependencies:
  pedantic: ^1.0.0
