name: music_notes
description: Music notes library
version: 0.1.0

author: albertms10
repository: https://github.com/albertms10/music_notes.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  quiver: ^3.0.0
  test: ^1.16.5

dev_dependencies:
  lints: ^1.0.1
